-- create the Disaster Risk Recovery schema

CREATE SCHEMA IF NOT EXISTS "drr";
GRANT SELECT,USAGE ON ALL TABLES IN SCHEMA "drr" TO "tileserver";
GRANT CREATE,USAGE ON SCHEMA "drr" TO "tileserver";
ALTER DEFAULT PRIVILEGES IN SCHEMA "drr" GRANT SELECT ON TABLES  TO "tileserver" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA "drr" GRANT SELECT ON TABLES  TO "tileserver";


